sudo: false
dist: trusty
language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0
# addons:
#   code_climate:
#     repo_token: $CODECLIMATE_REPO_TOKEN
cache:
  directories:
    - _build
    - deps
script:
  # Ensure gem dependencies are not outdated
  - mix hex.outdated
  # Run tests and coverage
  - mix coveralls
  # Run dogma code quality check
  - mix dogma
  # Run credo code quality check
  - mix credo --strict
  # Run dialyzer to ensure specs are correct
  # Extra options added in an attempt to speed up Travis builds. More info at:
  # http://blog.danielberkompas.com/elixir/2015/04/03/run-dialyzer-on-elixir-on-travis.html
  - mix dialyzer --halt-exit-status --no-check
# after_success:
  # Send results off to Code Climate
after_script:
  # Run inline documentation report
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
