sudo: false
dist: trusty
language: elixir
elixir:
  - 1.6.3
otp_release:
  - 20.2.4
cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test
script:
  # Ensure gem dependencies are not outdated
  - mix hex.outdated
  # Run tests and coverage on CI
  - mix coveralls.travis
  # Run credo code quality check
  - mix credo --strict
  # Run dialyzer to ensure specs are correct.
  # NOTE: --no-check option added to skip check on whether PLT file needs to be
  # updated. The version in the cached _build file will be used, hence not
  # slowing down the build while the PLT file gets rebuilt.
  # The --no-check option will have to be removed on a single build if Elixir
  # or Erlang versions update, but can then be re-instated.
  # - mix dialyzer --halt-exit-status
  - mix dialyzer --halt-exit-status --no-check
after_script:
  # Run inline documentation report
  - mix inch.report
